In [1]:
#Handle Categorical Features

In [2]:
import pandas as pd
import os

In [3]:
os.getcwd()

'C:\\Users\\EARABMO\\Desktop\\ERICSSON ITEMS\\DATA SCIENTIST\\PYTHON\\.ipynb_checkpoints\\Feature Engineering'

In [4]:
df=pd.read_csv("train.csv",usecols=["Sex"])

In [5]:
df.head()

Sex
0    male
1  female
2  female
3  female
4    male

In [6]:
pd.get_dummies(df,drop_first=True)

Sex_male
0           1
1           0
2           0
3           0
4           1
..        ...
886         1
887         0
888         0
889         1
890         1

[891 rows x 1 columns]

In [16]:
df=pd.read_csv("train.csv",usecols=["Embarked"])

In [17]:
df.head()

Embarked
0        S
1        C
2        S
3        S
4        S

In [18]:
df['Embarked'].unique()


array(['S', 'C', 'Q', nan], dtype=object)

In [19]:
df.dropna(inplace=True)

In [20]:
pd.get_dummies(df,drop_first=True).head()

Embarked_Q  Embarked_S
0           0           1
1           0           0
2           0           1
3           0           1
4           0           1

In [7]:
##### Onehotencoding with many categories in a feature

In [8]:
df=pd.read_csv('mercedesbenz.csv',usecols=["X0","X1","X2","X3","X4","X5","X6"])

In [9]:
df.head()

X0 X1  X2 X3 X4 X5 X6
0   k  v  at  a  d  u  j
1   k  t  av  e  d  y  l
2  az  w   n  c  d  x  j
3  az  t   n  f  d  x  l
4  az  v   n  f  d  h  d

In [32]:
#lets have a look how many labels of each variables"

for i in df.columns:
    print(len(df[i].unique()),"Labels")

47 Labels
27 Labels
44 Labels
7 Labels
4 Labels
29 Labels
12 Labels


In [14]:
#How many columns will obtain after one hot coding
d1=pd.get_dummies(df,drop_first=True).shape

In [16]:
d1


(4209, 163)

In [38]:
df.shape

(4209, 7)

In [41]:
#TOP 10 most frequent of categorial variables
df.X2.value_counts().sort_values(ascending=False).head(10)

as    1659
ae     496
ai     415
m      367
ak     265
r      153
n      137
s       94
f       87
e       81
Name: X2, dtype: int64

In [27]:
#Creating a list of most frequent variables into the mist
lst_10= [x for x in df.X1.value_counts().sort_values(ascending=False).head(10).index]
lst_10

['aa', 's', 'b', 'l', 'v', 'r', 'i', 'a', 'c', 'o']

In [26]:
#Vary the most frequent label that we have encode
import numpy as np
for categories in lst_10:
    df[categories]=np.where(df['X1']==categories,1,0)
df[["X1"]+lst_10].head()

X1  aa  s  b  l  v  r  i  a  c  o
0  v   0  0  0  0  1  0  0  0  0  0
1  t   0  0  0  0  0  0  0  0  0  0
2  w   0  0  0  0  0  0  0  0  0  0
3  t   0  0  0  0  0  0  0  0  0  0
4  v   0  0  0  0  1  0  0  0  0  0

In [50]:
#Toget the whole set of dummy variables,for all the categorials variables
def one_hot_top_x(df,variable,lst_10):
    for categories in lst_10:
        df[categories]=np.where(df['X1']==categories,1,0)
one_hot_top_x()

In [28]:
lst_10_X3= [x for x in df.X3.value_counts().sort_values(ascending=False).head(10).index]
lst_10_X3

['c', 'f', 'a', 'd', 'g', 'e', 'b']

In [31]:
#Toget the whole set of dummy variables,for all the categorials variables
def one_hot_top_x(df,variable,lst_10_X3):
    for categories in lst_10:
        df[categories]=np.where(df['X3']==categories,1,0)
one_hot_top_x(df,variable,lst_10_X3)

NameError: name 'variable' is not defined

# ONE HOT CODING VARAIBLE 
#ADVANTAGES:

#ADVANTAGES:
>Straight forward to implement
>Doesnot require hours of exploration
>Doesnot Require massively the feature space


#Disadvantages
>Donot add any information  that make the variable more  predictive 
>Donot keep the information of ignored lables


In [ ]:
# example of a ordinal encoding
from numpy import asarray
from sklearn.preprocessing import OrdinalEncoder
# define data
data = asarray([['red'], ['green'], ['blue']])
print(data)
# define ordinal encoding
encoder = OrdinalEncoder()
# transform data
result = encoder.fit_transform(data)
print(result)


In [40]:
#Each bit represents a possible category. If the variable cannot belong to multiple categories at once,
#then only one bit in the group can be “on.” This is called one-hot encoding 
# example of a one hot encoding
#This one-hot encoding transform is available in the scikit-learn Python machine learning library via the OneHotEncoder class.
from numpy import asarray
from sklearn.preprocessing import OneHotEncoder
# define data
data = asarray([['red'], ['green'], ['blue']])
print(data)
# define one hot encoding
encoder = OneHotEncoder(sparse=False)
# transform data
onehot = encoder.fit_transform(data)
print(onehot)

[['red']
 ['green']
 ['blue']]
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


# Dummy Variable Encoding

In [41]:
#The one-hot encoding creates one binary variable for each category.
#hen there are C possible values of the predictor and only C – 1 dummy variables are used, the matrix inverse can be computed and 
#the contrast method is said to be a full rank parameterization.

# example of a dummy variable encoding
from numpy import asarray
from sklearn.preprocessing import OneHotEncoder
# define data
data = asarray([['red'], ['green'], ['blue']])
print(data)
# define one hot encoding
encoder = OneHotEncoder(drop='first', sparse=False)#Sparse=True it will return matrix otherwise false return array
# transform data
onehot = encoder.fit_transform(data)
print(onehot)

[['red']
 ['green']
 ['blue']]
[[0. 1.]
 [1. 0.]
 [0. 0.]]


# Breast Cancer Dataset

In [48]:
# load and summarize the dataset
from pandas import read_csv
# define the location of the dataset
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/breast-cancer.csv"
# load the dataset
dataset = read_csv(url, header=None)
# retrieve the array of data
data = dataset.values
# separate into input and output columns
X = data[:, :-1].astype(str)
y = data[:, -1].astype(str)
# summarize
print('Input', X.shape)
print('Output', y.shape)

Input (286, 9)
Output (286,)


In [51]:
X

array([["'40-49'", "'premeno'", "'15-19'", ..., "'right'", "'left_up'",
        "'no'"],
       ["'50-59'", "'ge40'", "'15-19'", ..., "'right'", "'central'",
        "'no'"],
       ["'50-59'", "'ge40'", "'35-39'", ..., "'left'", "'left_low'",
        "'no'"],
       ...,
       ["'30-39'", "'premeno'", "'30-34'", ..., "'right'", "'right_up'",
        "'no'"],
       ["'50-59'", "'premeno'", "'15-19'", ..., "'right'", "'left_low'",
        "'no'"],
       ["'50-59'", "'ge40'", "'40-44'", ..., "'left'", "'right_up'",
        "'no'"]], dtype='<U11')

In [52]:
y

array(["'recurrence-events'", "'no-recurrence-events'",
       "'recurrence-events'", "'no-recurrence-events'",
       "'recurrence-events'", "'no-recurrence-events'",
       "'no-recurrence-events'", "'no-recurrence-events'",
       "'no-recurrence-events'", "'no-recurrence-events'",
       "'no-recurrence-events'", "'no-recurrence-events'",
       "'no-recurrence-events'", "'no-recurrence-events'",
       "'recurrence-events'", "'no-recurrence-events'",
       "'no-recurrence-events'", "'no-recurrence-events'",
       "'no-recurrence-events'", "'no-recurrence-events'",
       "'recurrence-events'", "'no-recurrence-events'",
       "'no-recurrence-events'", "'no-recurrence-events'",
       "'recurrence-events'", "'no-recurrence-events'",
       "'no-recurrence-events'", "'no-recurrence-events'",
       "'no-recurrence-events'", "'recurrence-events'",
       "'recurrence-events'", "'no-recurrence-events'",
       "'no-recurrence-events'", "'no-recurrence-events'",
       "'recurrence-e

# OrdinalEncoder Transform

In [1]:
#An ordinal encoding involves mapping each unique label to an integer value

In [ ]:
# ordinal encode the breast cancer dataset
from pandas import read_csv
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder
# define the location of the dataset
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/breast-cancer.csv"
# load the dataset
dataset = read_csv(url, header=None)
# retrieve the array of data
data = dataset.values
# separate into input and output columns
X = data[:, :-1].astype(str)
y = data[:, -1].astype(str)
# ordinal encode input variables
ordinal_encoder = OrdinalEncoder()
X = ordinal_encoder.fit_transform(X)
# ordinal encode target variable
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)
# summarize the transformed data
print('Input', X.shape)
print(X[:5, :])
print('Output', y.shape)
print(y[:5])

In [6]:
import pandas as pd
from pandas import read_csv
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder
# define the location of the dataset
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/breast-cancer.csv"
# load the dataset
dataset = read_csv(url, header=None)
data=dataset.values
X = data[:, :-1].astype(str)
y = data[:, -1].astype(str)
ordinal_encoder = OrdinalEncoder()
X = ordinal_encoder.fit_transform(X)
# ordinal encode target variable
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)



In [14]:
ordinal_encoder.transform(X_train)
#X_test = ordinal_encoder.transform(X_test)

array([[ 3.,  0.,  4., ...,  0.,  3.,  0.],
       [ 1.,  2.,  9., ...,  0.,  3.,  0.],
       [ 3.,  2., 10., ...,  1.,  2.,  1.],
       ...,
       [ 4.,  0.,  1., ...,  1.,  1.,  0.],
       [ 4.,  0.,  7., ...,  1.,  1.,  0.],
       [ 4.,  0.,  8., ...,  0.,  0.,  0.]])

In [15]:
# evaluate logistic regression on the breast cancer dataset with an ordinal encoding
from numpy import mean
from numpy import std
from pandas import read_csv
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.metrics import accuracy_score
# define the location of the dataset
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/breast-cancer.csv"
# load the dataset
dataset = read_csv(url, header=None)
# retrieve the array of data
data = dataset.values
# separate into input and output columns
X = data[:, :-1].astype(str)
y = data[:, -1].astype(str)
# split the dataset into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1)
# ordinal encode input variables
ordinal_encoder = OrdinalEncoder()
ordinal_encoder.fit(X_train)
X_train = ordinal_encoder.transform(X_train)
X_test = ordinal_encoder.transform(X_test)
# ordinal encode target variable
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
y_train = label_encoder.transform(y_train)
y_test = label_encoder.transform(y_test)
# define the model
model = LogisticRegression()
# fit on the training set
model.fit(X_train, y_train)
# predict on test set
yhat = model.predict(X_test)
# evaluate predictions
accuracy = accuracy_score(y_test, yhat)
print('Accuracy: %.2f' % (accuracy*100))

Accuracy: 73.68


c:\users\earabmo\appdata\local\programs\python\python38-32\lib\site-packages\sklearn\linear_model\logistic.py:430: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  warnings.warn("Default solver will be changed to 'lbfgs' in 0.22. "


# OneHotEncoder Transform

In [ ]:
# evaluate logistic regression on the breast cancer dataset with an one-hot encoding
from numpy import mean
from numpy import std
from pandas import read_csv
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import accuracy_score
# define the location of the dataset
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/breast-cancer.csv"
# load the dataset
dataset = read_csv(url, header=None)
# retrieve the array of data
data = dataset.values
# separate into input and output columns
X = data[:, :-1].astype(str)
y = data[:, -1].astype(str)
# split the dataset into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1)
# one-hot encode input variables
onehot_encoder = OneHotEncoder()
onehot_encoder.fit(X_train)
X_train = onehot_encoder.transform(X_train)
X_test = onehot_encoder.transform(X_test)
# ordinal encode target variable
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
y_train = label_encoder.transform(y_train)
y_test = label_encoder.transform(y_test)
# define the model
model = LogisticRegression()
# fit on the training set
model.fit(X_train, y_train)
# predict on test set
yhat = model.predict(X_test)
# evaluate predictions
accuracy = accuracy_score(y_test, yhat)
print('Accuracy: %.2f' % (accuracy*100))